import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const TERRAINS=['Plaine ouverte','Forêt dense','Ruines','Ville','Montagne','Marais','Désert','Caverne','Arène fermée','Zone aquatique'];
const DISTANCES:[string,number][]=[['Corps à corps',2],['Courte distance',8],['Distance moyenne',25],['Longue distance',60]];
const KNOWLEDGE=['Aucune information','Informations partielles','Bonne connaissance de l’adversaire'];
const REGIONS:[string,string][]=[['Sylvaeryn','sylvaeryn'],['Kharadryn','kharadryn'],['Avelorn','avelorn'],['Drakhenor','drakhenor'],['Maelora','maelora'],['Iskarya','iskarya'],['Nexara','nexara'],['Kaelora','kaelora'],['Vaerunn','vaerunn'],['Aetherys','aetherys'],['Thoryndra','thoryndra'],['Liorael','liorael'],['Caelorn','caelorn'],['Varkhoryn','varkhoryn'],['Kythera','kythera'],['Lumerys','lumerys'],['Naeroth','naeroth'],["Mor'Khal",'morkhal']];
function out(x:any,status=200){return new Response(JSON.stringify(x),{status,headers:{...CORS,"Content-Type":"application/json"}})}
function meta(v:any){if(v&&typeof v==='object')return v;if(typeof v==='string')try{return JSON.parse(v)}catch{}return{}}
function isChampion(ch:any,id:string){return Object.values(ch||{}).some((c:any)=>String(c?.id??c?.characterId??c?.character_code??'')===id)}
function pick<T>(a:T[]):T{return a[Math.floor(Math.random()*a.length)]}
function value(c:any,ctx:any){const st=c?.stats||{},combat=+st.Combat||0,force=+st.Force||0,intel=+st.Intelligence||0,res=+st['Résilience']||0,vit=+st['Vitesse']||0;const ps=(c?.powers||[]).map((p:any)=>+p.mastery||0);if(c?.chi?.rank)ps.push(+c.chi.rank||0);const ws=(c?.weapons||[]).map((w:any)=>+w.mastery||0);const p=ps.length?Math.max(...ps):0,w=ws.length?Math.max(...ws):0;let v=combat*2.2+force*1.15+intel*1.15+res*1.45+vit*1.35+p*1.7+w*1.25;const arch=String(c?.arch||'');if(ctx.distance>=25){if(/Tireur|Mage|Sorcier/.test(arch))v+=4;if(/Assassin|Berserker|Artiste martial/.test(arch))v-=2}if(ctx.distance<=8){if(/Artiste martial|Berserker|Guerrier|Assassin/.test(arch))v+=3;if(/Tireur/.test(arch))v-=2}if(ctx.terrain==='Forêt dense'||ctx.terrain==='Ruines'){if(/Chasseur|Éclaireur|Assassin|Trickster/.test(arch))v+=2}if(ctx.terrain==='Plaine ouverte'){if(/Tireur|Commandant/.test(arch))v+=2}if(ctx.terrain==='Zone aquatique'&&String(c?.race||'').match(/Requin|Baleine|Poulpe|Kraken|Serpent de mer|Léviathan/i))v+=5;return v}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return out({error:'Method not allowed'},405);try{const url=Deno.env.get('SUPABASE_URL'),anon=Deno.env.get('SUPABASE_ANON_KEY'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),auth=req.headers.get('Authorization');if(!url||!anon||!service)return out({error:'Configuration Supabase manquante.'},500);if(!auth)return out({error:'Utilisateur non authentifié.'},401);const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),{data:{user},error:ue}=await uc.auth.getUser();if(ue||!user)return out({error:'Session invalide.'},401);const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),body=await req.json().catch(()=>({})),action=String(body?.action||'');
const profile=async(id:string)=>{const {data,error}=await db.from('player_profiles').select('user_id,username').eq('user_id',id).maybeSingle();if(error)throw new Error('Impossible de lire le profil joueur.');return data||null};
const publicMatch=async(m:any)=>{if(!m)return null;const ids=[m.player1_id,m.player2_id].filter(Boolean);const {data}=ids.length?await db.from('player_profiles').select('user_id,username').in('user_id',ids):{data:[] as any[]};const names=new Map((data||[]).map((p:any)=>[p.user_id,p.username]));return {...m,player1_username:names.get(m.player1_id)||null,player2_username:names.get(m.player2_id)||null}};
const requireProfile=async()=>{const p=await profile(user.id);if(!p?.username)throw new Error('Crée un pseudo avant de lancer un duel en ligne.');return p};
const stats=async()=>{const {data}=await db.from('multiplayer_duel_stats').select('victories,defeats,recent_duels').eq('user_id',user.id).maybeSingle();return data||{victories:0,defeats:0,recent_duels:[]}};
if(['status','search','select_champion','resolve'].includes(action))await requireProfile();
if(action==='status'){const {data,error}=await db.from('multiplayer_duel_matches').select('*').or(`player1_id.eq.${user.id},player2_id.eq.${user.id}`).order('created_at',{ascending:false}).limit(1);if(error)return out({error:'Impossible de lire le matchmaking.'},500);const m=data?.[0]||null;return out({ok:true,status:m?.status||'idle',match:await publicMatch(m),stats:await stats()})}
if(action==='cancel'){await db.from('multiplayer_duel_matches').delete().eq('player1_id',user.id).eq('status','waiting');return out({ok:true,status:'idle',stats:await stats()})}
if(action==='search'){const {data:ex}=await db.from('multiplayer_duel_matches').select('*').or(`player1_id.eq.${user.id},player2_id.eq.${user.id}`).in('status',['waiting','matched','ready','resolving']).order('created_at',{ascending:false}).limit(1);if(ex?.length)return out({ok:true,status:ex[0].status,match:await publicMatch(ex[0]),stats:await stats()});const {data:w}=await db.from('multiplayer_duel_matches').select('*').eq('status','waiting').neq('player1_id',user.id).order('created_at',{ascending:true}).limit(1);if(w?.[0]){const {data:m,error}=await db.from('multiplayer_duel_matches').update({player2_id:user.id,status:'matched',updated_at:new Date().toISOString()}).eq('id',w[0].id).eq('status','waiting').is('player2_id',null).select();if(error)return out({error:'Impossible de créer le duel.'},500);if(!m?.length)return out({ok:true,status:'retry'});return out({ok:true,status:'matched',match:await publicMatch(m[0]),stats:await stats()})}const {data:m,error}=await db.from('multiplayer_duel_matches').insert({player1_id:user.id,status:'waiting'}).select().single();if(error)return out({error:'Impossible de démarrer la recherche.'},500);return out({ok:true,status:'waiting',match:await publicMatch(m),stats:await stats()})}
if(action==='select_champion'){const gameId=String(body?.gameId||''),championId=String(body?.championId||'');if(!gameId||!championId)return out({error:'gameId et championId sont obligatoires.'},400);const {data:ms}=await db.from('multiplayer_duel_matches').select('*').or(`player1_id.eq.${user.id},player2_id.eq.${user.id}`).in('status',['matched','ready']).order('created_at',{ascending:false}).limit(1);const m=ms?.[0];if(!m)return out({error:'Aucun duel actif trouvé.'},404);const {data:g}=await db.from('games').select('id,owner_id,universe_meta').eq('id',gameId).eq('owner_id',user.id).maybeSingle();if(!g)return out({error:"Cette partie n'appartient pas au joueur connecté."},403);if(!isChampion(meta(g.universe_meta)?.champions,championId))return out({error:"Ce personnage n'est pas un champion de cette partie."},403);const {data:c}=await db.from('characters').select('data').eq('game_id',gameId).eq('character_code',championId).maybeSingle();if(!c)return out({error:'Champion introuvable.'},404);const snap={gameId,championId,character:c.data},field=m.player1_id===user.id?'player1_champion':'player2_champion';const {data:u,error}=await db.from('multiplayer_duel_matches').update({[field]:snap,updated_at:new Date().toISOString()}).eq('id',m.id).select().single();if(error)return out({error:"Impossible d'enregistrer le champion."},500);if(u.player1_champion&&u.player2_champion){const {data:r}=await db.from('multiplayer_duel_matches').update({status:'ready',updated_at:new Date().toISOString()}).eq('id',m.id).select().single();return out({ok:true,status:'ready',match:await publicMatch(r),stats:await stats()})}return out({ok:true,status:'matched',match:await publicMatch(u),stats:await stats()})}
if(action==='resolve'){const {data:ms}=await db.from('multiplayer_duel_matches').select('*').or(`player1_id.eq.${user.id},player2_id.eq.${user.id}`).eq('status','ready').order('created_at',{ascending:false}).limit(1);const m=ms?.[0];if(!m)return out({error:'Aucun duel prêt à résoudre.'},404);const {data:locked}=await db.from('multiplayer_duel_matches').update({status:'resolving',updated_at:new Date().toISOString()}).eq('id',m.id).eq('status','ready').select();if(!locked?.length)return out({error:'Ce duel est déjà en cours de résolution.'},409);const A=m.player1_champion?.character,B=m.player2_champion?.character,a=m.player1_champion?.championId,b=m.player2_champion?.championId;if(!A||!B||!a||!b)return out({error:'Champions incomplets.'},400);const terrain=pick(TERRAINS),d=pick(DISTANCES),r=pick(REGIONS),ctx={terrain,distance:d[1],distanceLabel:d[0],region:r[0],regionSlug:r[1],knowledgeA:pick(KNOWLEDGE),knowledgeB:pick(KNOWLEDGE)};let va=value(A,ctx),vb=value(B,ctx);if(ctx.knowledgeA==='Informations partielles')va+=1.5;else if(ctx.knowledgeA==='Bonne connaissance de l’adversaire')va+=3;if(ctx.knowledgeB==='Informations partielles')vb+=1.5;else if(ctx.knowledgeB==='Bonne connaissance de l’adversaire')vb+=3;const probA=Math.max(.1,Math.min(.9,1/(1+Math.exp(-(va-vb)/10)))),winner=Math.random()<probA?a:b,winUser=winner===a?m.player1_id:m.player2_id,loseUser=winUser===m.player1_id?m.player2_id:m.player1_id;const pm=await publicMatch(m),p1name=pm?.player1_username||'Joueur',p2name=pm?.player2_username||'Joueur';const battle={a,b,winner,loser:winner===a?b:a,region:ctx.region,regionSlug:ctx.regionSlug,terrain,distanceLabel:ctx.distanceLabel,distance:ctx.distance,knowledgeA:ctx.knowledgeA,knowledgeB:ctx.knowledgeB,probA:+probA.toFixed(4),at:new Date().toISOString(),player1Username:p1name,player2Username:p2name,characterA:{name:A?.name||a},characterB:{name:B?.name||b}};const h1={won:winUser===m.player1_id,opponent:m.player2_id,opponentUsername:p2name,champion:a,championName:A?.name||a,opponentChampion:b,opponentName:B?.name||b,region:ctx.region,terrain,at:battle.at,battle},h2={won:winUser===m.player2_id,opponent:m.player1_id,opponentUsername:p1name,champion:b,championName:B?.name||b,opponentChampion:a,opponentName:A?.name||a,region:ctx.region,terrain,at:battle.at,battle};const {error:fe}=await db.rpc('finalize_multiplayer_duel',{p_match_id:m.id,p_winner_id:winUser,p_loser_id:loseUser,p_player1_history:h1,p_player2_history:h2});if(fe){await db.from('multiplayer_duel_matches').update({status:'ready'}).eq('id',m.id);return out({error:'Impossible de finaliser le duel : '+fe.message},500)}return out({ok:true,status:'completed',battle,stats:await stats()})}
return out({error:'Action inconnue.'},400)}catch(e){console.error(e);return out({error:e instanceof Error?e.message:'Erreur serveur inconnue.'},500)}});
